### ISSUE TITLE
[question] Support for Document API in DynamoDB

### ISSUE THREAD

**Issue by SaxyPandaBear** [aws/aws-dynamodb-encryption-java#131]
Does this library support the [Document](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.SDKs.Interfaces.Document.html) API that is provided by the DynamoDB SDK? I'm asking because (1) I didn't see it mentioned in the README, and (2) I have inherited some code that uses a custom encryption strategy because there was a decision made at the time (this was in 2016-2017) to use the Document client for DDB rather than the Object mapper, like what is described in the README example for this repo.

**Comment by farleyb-amazon** [comment]
Hi, apologies for the slow response here.

The DynamoDB Encryption client can be used with the DynamoDB Document API by first using the DynamoDBEncryptor interface on the Encryption Client to encrypt the records, then using the [ItemUtils](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/document/ItemUtils.html#toItem-java.util.Map-) helper to convert this to the `Item` type that the Document API understands.

Something like:
```
// Set up DDB Encryption Client
final DynamoDBEncryptor encryptor = ...

// Create a record to encrypt
final Map<String, AttributeValue> record = ...

// Encrypt the record using DDB Encryption Client
final Map<String, AttributeValue> encryptedRecord = encryptor.encryptRecord(record, ...);

// Set up the DDB document client
AmazonDynamoDB client = AmazonDynamoDBClientBuilder.standard().build();
DynamoDB docClient = new DynamoDB(client);
Table table = docClient.getTable("myTableName");

// Convert Map to Item
Item encryptedItem = ItemUtils.toItem(encryptedRecord)

// Store using Document API
PutItemOutcome outcome = table.putItem(encryptedItem);
```
For more details on configuring the DDB Encryption Client, see the example on using the [DynamoDBEncryptor](https://docs.aws.amazon.com/dynamodb-encryption-client/latest/devguide/java-examples.html).

I'm going to go ahead and close this out, but feel free to re-open or cut another issue if you have any other questions.

Thanks,
Ben
