### ISSUE TITLE
Size of Material Description and Signature

### ISSUE THREAD

**Issue by adamcyber1** [aws/aws-dynamodb-encryption-java#153]
Hello, is there a size (or a size range? at the very least a max) of the material description attribute? 

I cannot seem to find this anywhere in the documentation, but it is a very useful consideration because it impacts customer data usage. 

The size of the signature that is added to the table item would also be helpful.

**Comment by shreelakshmijoshi** [comment]
Hi @adamcyber1 !
I am a new open source contributor and would love to solve this issue, could you help me understand the issue better by providing some extra references ? 
Is this is issue open to contribute ?

**Comment by lavaleri** [comment]
Hi @adamcyber1 

The material description is a serialization of key value pairs that gets base64 encoded. The potential key values are:

- "amzn-ddb-map-sym-mode"
- "amzn-ddb-map-signingAlg"
- "amzn-ddb-env-key"
- "amzn-ddb-env-alg"
- "amzn-ddb-wrap-alg"
- "amzn-ddb-sig-alg"

Which key values are included in the matdesc and what the corresponding values are (and how large those values are) will depend on the material provider in use.

Here is an example material description I get from using the DirectKmsMaterialProvider:
AAAAAAAAABBhbXpuLWRkYi1lbnYta2V5AAAA+EFRSUJBSGk3WjFMQVNjb1ZpRHJGdjdQL1ZabkhPT1JrTDZiZFBsOFRCaFZMZEV2Z05nR1RqZDdmNU8wU2Z1clNmbThlQjhuMkFBQUFmakI4QmdrcWhraUc5dzBCQndhZ2J6QnRBZ0VBTUdnR0NTcUdTSWIzRFFFSEFUQWVCZ2xnaGtnQlpRTUVBUzR3RVFRTTFldjVyL1dSWWw3SWcwUE1BZ0VRZ0RzYkJKVENXby9VTm1WS2xzbVY2QTNYMkhxS3ZxN2xYbUkyWHFGVEdZU2RDalR2SGRQYlRXQnZtNWZXL0REaFpuVUxLSmhKRkJFcWU2cWlxQT09AAAAD2F3cy1rbXMtZWMtYXR0cgAAAAYqa2V5cyoAAAAQYW16bi1kZGItZW52LWFsZwAAAAdBRVMvMjU2AAAAEGFtem4tZGRiLXNpZy1hbGcAAAAOSG1hY1NIQTI1Ni8yNTYAAAARYW16bi1kZGItd3JhcC1hbGcAAAADa21zAAAAFWFtem4tZGRiLW1hcC1zeW0tbW9kZQAAABEvQ0JDL1BLQ1M1UGFkZGluZw==

The serialization includes 4 bytes to indicate a format version, and 4 bytes per key/value to indicate the length. The exact serialization logic lives here if you need more detail: https://github.com/aws/aws-dynamodb-encryption-java/blob/master/sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DynamoDBEncryptor.java#L526

The size of the signature attribute depends on what material provider is being used, as that will determine the signature algorithm. For example, the signature algorithm used with the DirectKmsMaterialProvider is `HmacSha256 `. After being Base64 encoded, this should result in a value that is 44 bytes long.
