### ISSUE TITLE
Support Point in time restore with client side encryption 

### ISSUE THREAD

**Issue by akshatvi** [aws/aws-dynamodb-encryption-java#39]
Point in time restore takes table name as an input. In DynamoDB if a table already exists you can not overwrite the table data by doing a restore, you have to restore to new table with a different name. 

If customers were using client side encryption library all the data items will be signed using the table name and stored with the item. If they do a point in time restore on this table restoring the table to a new table name will mean the restored data is not readable as the signatures stored on the items would fail to verify. 

We need some way for customers to be able to specify that they want to use the older table name for the restored table so that they can still read and write data to the DynamoDB table even though it was restored as a new table.

**Comment by SalusaSecondus** [comment]
Note:
* This already works when the `DynamoDBEncryptor` is used directly
* In some (simple) cases `@TableAadOverride` will properly fix this by forcing the table name (in the signature) to be a constant for a given class, regardless of actual table used.

There is not currently a way to dynamically tell the `AttributeEncryptor` via the `DynamoDBMapper` to use a specific table name for the signature  separate from the table actually being used for data storage.

**Comment by mattsains** [comment]
What do you mean by "when the `DynamoDBEncryptor` is used directly"? How is this different from indirectly?

**Comment by michaelzhd** [comment]
> * This already works when the `DynamoDBEncryptor` is used directly
It only works for regular tables but not MetaStore tables. For MetaStore, table is fixed for encryption or signing:
https://github.com/aws/aws-dynamodb-encryption-java/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/store/MetaStore.java#L85

**Comment by johnwalker** [comment]
Overriding the table name for DynamoDBMapper is supported as of `1.13.0` through `setEncryptionContextOverrideOperator` on `DynamoDBEncryptor`. DynamoDBEncryptors that override the `EncryptionContext` can be supplied to `AttributeEncryptor` or `MetaStore` to support PITR. 

See: https://github.com/aws/aws-dynamodb-encryption-java/blob/master/examples/com/amazonaws/examples/EncryptionContextOverridesWithDynamoDBMapper.java#L62-78 for an example with the mapper.

Please let us know what you think!
