### ISSUE TITLE
Question: will decrypting still work after KMS keys are rotated.

### ISSUE THREAD

**Issue by mik373** [aws/aws-dynamodb-encryption-java#40]
We'd like to use the automatic key rotation on the KMS keys that are used to encrypt data in out Dynamo tables: https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html#rotate-keys-how-it-works.  We've tested that the data can be decrypted if a new KMS key is created and the key alias is pointing to it, however testing when the actual backing key is rotated is not possible since AWS rotates the keys 365 days after the rotation is enabled.  Can you please provide the details on how decrypting the data that was saved with the old backing key will work?

**Comment by mattsb42-aws** [comment]
We actually have recently revamped docs about this here[1]. The short answer is that the CMK rotation is entirely transparent to you as a user. The CMK retains the same Arn and KMS retains the old versions of your CMK material and will select the correct one to use on decrypt.

[1] https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html

**Comment by SalusaSecondus** [comment]
Closing this as asked and answered.
