### ISSUE TITLE
AWS SDK for Java 2.0 compatibility

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-dynamodb-encryption-java#41]
## Problem
The AWS SDK for Java 2.0 will involve a significant change in that library's API and namespaces. We need to determine the right approach to ensuring compatibility with both the 1.0 and 2.0 libraries without incurring too many issues with code duplication.`

**Comment by josecorella** [comment]
No plans to support AWS SDK Java 2.0 in the dynamo encryption client
