### ISSUE TITLE
Document how to run examples

### ISSUE THREAD

**Issue by johnwalker** [aws/aws-dynamodb-encryption-java#61]
This command works for running examples, assuming that the target class has already been compiled.

```
mvn exec:java -Dexec.mainClass="com.amazonaws.examples.TheExample" -Dexec.arguments="arg1","arg2,"arg3" -Dexec.cleanupDaemonThreads=false -q
```

A wrapper around this command should be provided to run examples, and how to do it should be documented. The wrapper should depend on a compilation step for the examples.

**Comment by josecorella** [comment]
Stale Issue, closing
