### ISSUE TITLE
Support for Global Tables

### ISSUE THREAD

**Issue by pluttrell** [aws/aws-dynamodb-encryption-java#68]
Is there a strategy for using the client-side encryption provided by this library with items that have been replicated to other regions using Global Tables _and_ AWS KMS originated CMKs?

**Comment by mattsb42-aws** [comment]
Hi @pluttrell,

We don't have a good story for using this client with Global Tables at this time. It would work as long as you told it to ignore the attributes that Global Tables creates but it would require a cross-region call to KMS in the source region when any item is read.

If you want to use this client with regionally replicated tables and decrypt in-region, you will currently need to do some level of replication and re-encryption yourself.

Regional data portability is something we have high on our list of priorities for the long-term development of the DDB encryption client. I'll add this as reference for customer demand in the prioritization of that development.

**Comment by pluttrell** [comment]
Hi @mattsb42-aws,

Thanks for getting back to me and for taking this request into consideration for future priorities. This solution would work great for us if it worked today. As Global Tables gets additional customers, I'd imagine many others would need this as well.

You mentioned to get this to work today that we'd need to do a cross-region call to the KMS in the source region when any item is read. Two things: 

1. I can't get it to work out of the box. When I access DynamoDB from the replicated region, yet initialize the `DirectKmsMaterialProvider` with an ARN that points to the same CMK in the origin region, I get the following error:

```
com.amazonaws.services.kms.model.AWSKMSException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access. (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID: e80ae725-c210-45b8-affb-145406bde32c)
```

2. Making a cross-region call makes sense if we choose the _Direct KMS Provider_ for the Cryptographic Materials Provider, as it requires individual data key retrievals within the in region for all reads. The latency for cross-region calls would certainly be prohibitive in our use case and also introduce a single point of failure, which we're trying to avoid by using Global Tables. I'm wondering if instead we chose the _Most Recent Provider_ with a long ttl (not what we'd like to choose), wouldn't we have a high likelihood of cache hits for the data keys since these are cached in the in-memory MetaStore?

Thanks,
Peter

**Comment by mattsb42-aws** [comment]
> com.amazonaws.services.kms.model.AWSKMSException: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access. (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID: e80ae725-c210-45b8-affb-145406bde32c)

This means that either the CMK your configured it with does not exist or the principal (Role/User) you are using does not have permissions to use the CMK. Are you using the same principal as you did in the source region? If not, have you verified that the second principal has access to the CMK?

> Most Recent Provider

This would work, yes. You would still have to deal with cross-region calls whenever the `MostRecentProvider` retrieves keys from the `MetaStore` table, though.

**Comment by gthicks** [comment]
Has there been any movement on this feature?

**Comment by artkinghur** [comment]
Has there been any movement on this particular feature? If not, what is the recommended multi-region strategy?

**Comment by SalusaSecondus** [comment]
We have not made any changes here yet. The current advice is still captured by @mattsb42-aws's comments above.

**Comment by RobertoC27** [comment]
We have just stumbled across the same issue, cross-region replication with encrypted fields become a pain point for DR strategies. I've seen some guys suggest [doing manual encryption](https://stackoverflow.com/questions/40512477/dynamodb-can-we-use-encryption-and-cross-region-replication-together), any advice on how to achieve this?

**Comment by texastony** [comment]
@RobertoC27 We recommend that you consider [AWS KMS Multi-Region Keys (MRK)](https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html), which can be used seamlessly with the AWS DynamoDB Encryption client for Java.

See our [example](https://github.com/aws/aws-dynamodb-encryption-java/blob/master/examples/src/main/java/com/amazonaws/examples/AwsKmsMultiRegionKey.java) which uses multi-Region keys with a global table to encrypt and write a record in one Region, and then read and decrypt it from another Region. 

@gthicks, @artkinghur, as well as @pluttrell , we regret not commenting/referencing this issue sooner. KMS has released multi-Region keys, which resolve the issue of cross-Region calls. KMS MRKs allow for data encrypted in one region to be decrypted in another. 

Note that [#70](https://github.com/aws/aws-dynamodb-encryption-java/issues/70) is still  an issue if you are using Global Tables version 2017.11.29 with the DynamoDB Encryption library. [See more about how Global Tables version 2017.11.29 here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/globaltables_HowItWorks.html).

There are no complications with using the DynamoDB Encryption Library with Global Tables version 2019.11.21.

If y'all have any other questions or concerns about global table support or use with AWS DynamoDB Encryption client for Java, please re-open this issue or open a new issue.

Much obliged,
AWS Crypto Tools
