### ISSUE TITLE
Unable to encrypt specific field in a list of objects

### ISSUE THREAD

**Issue by RajuReddy7777** [aws/aws-dynamodb-encryption-java#837]
We can do either encrypting whole list or leaving the whole list with using **@DoNotTouch**. Our need is to encrypt specific field in the List<Object> which is not working.

In the below example, how can we encrypt only the **_phoneNumber_** in the **bookAuthors**;

```
@DynamoDBTable(tableName="Book")
   public class Book {
       private Integer id;
      @DoNotTouch private String title;
      @DoNotTouch private String ISBN;
      private Set<Author> bookAuthors;
     @DoNotTouch private String someProp;
    
     public class Author {
         private Integer id;
         private String name;
         private Integer phoneNumber;
         private Integer numberOfBooks;
     }
   }
```

**Comment by josecorella** [comment]
Hello @RajuReddy7777!

Unfortunately the DynamoDB Encryption Client is not able to handle this use case.
The DynamoDBMapper and DynamoDBEncryptor are not able to work with nested POJOs; they will end up treating it as only one attribute and encrypt/sign/do nothing the entire field.

— AWS Crypto Tools
