### ISSUE TITLE
Re-enable Parallel Scan Integration Tests

### ISSUE THREAD

**Issue by johnwalker** [aws/aws-dynamodb-encryption-java#84]
There are two tests that are disabled in `ScanITCase`, which work on regular DynamoDB, but sometimes fail on DynamoDBLocal.

We should figure out why they break between regular DynamoDB and DynamoDBLocal. If they can't run on DynamoDBLocal, they should run on regular DynamoDB in a separate test group from travis.

**Comment by josecorella** [comment]
Stale Issue, closing issue.
No tests disabled in ScanITCase.
