### ISSUE TITLE
Add option for running integration tests against DynamoDB instead of DynamoDBLocal

### ISSUE THREAD

**Issue by johnwalker** [aws/aws-dynamodb-encryption-java#85]
Some unit tests and integration tests run against DynamoDBLocal. We should include a command-line argument to pick which DynamoDB is targeted, so that DynamoDBLocal may be used on Travis and the real DynamoDB may be used during release. This will help us run more realistic tests.

**Comment by johnwalker** [comment]
@seebees suggested trying https://www.npmjs.com/package/dynalite, since it might be more similar to the real dynamodb. We can probably include support for each of these (local + Dynalite + ddb) without any additional effort.

**Comment by josecorella** [comment]
No longer using Travis for CI/CD, and now using DynamoDB for testing.
