### ISSUE TITLE
Support DoNotEncrypt/DoNotTouch field level annotations

### ISSUE THREAD

**Issue by wjnicholson** [aws/aws-dynamodb-encryption-java#94]
They're only targeting `ElementType.METHOD` at the moment, unlike `DynamoDbAttribute` which can be on a `ElementType.FIELD`.

The project I'm working on makes use of code generation on field properties and we annotate the fields with their dynamo information directly. I'd rather not have to hand write the getters with their annotation separate to the field definition, breaking our code generation.

Having a look at the code for SDK V1 it seems like this could be relatively straight forward (albeit with extra reflection) by checking in `shouldEncryptAttribute`
```
StandardAnnotationMaps.of(mapping.getter(), null)
            .actualOf(DoNotEncrypt.class) != null;
``` 
on the mapping.

**Comment by karlw00t** [comment]
looks like the PR was merged. Thanks, and closing.
